server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: HOTEL-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    

  config:
   import: configserver:http://localhost:8085   
    
#eureka:
#  instance:
#  prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
    
    
